BEGIN_REPLY = 1
HOW_IT_WORKS = 2
CHANGE_LANGUAGE = 3
I_NEED_HELP = 4
SEND_PACKS = 5
STAR_RATING = 6
READY_FOR_IMAGE_UPLOAD = 11
UPLOAD_MORE_IMAGES = 12
SHOW_EXAMPLES = 13
SHOW_PACK_IMAGES = 14
OVERRIDE_TUNE = 15
SEND_TUNES = 16
SET_TUNE = 17
GET_PAYMENT_LINK = 18
CONTACT_SUPPORT = 19
LITE_PACK = 20
STANDARD_PACK = 21
PREMIUM_PACK = 22




